"""empty message

Revision ID: 96412212a4cc
Revises: 38ce2e968356
Create Date: 2020-03-07 13:19:48.518109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96412212a4cc'
down_revision = '38ce2e968356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
