"""empty message

Revision ID: aae227835743
Revises: 11cfe8938f13
Create Date: 2020-03-06 23:23:17.578361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae227835743'
down_revision = '11cfe8938f13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue_description', sa.String(), nullable=True))
    op.drop_column('Artist', 'seeking_talent')
    op.drop_column('Artist', 'seeking_talent_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_talent_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking_venue_description')
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
